# coding: utf-8

"""
    Cloudbreak API

    Cloudbreak is a powerful left surf that breaks over a coral reef, a mile off southwest the island of Tavarua, Fiji. Cloudbreak is a cloud agnostic Hadoop as a Service API. Abstracts the provisioning and ease management and monitoring of on-demand clusters. SequenceIQ's Cloudbreak is a RESTful application development platform with the goal of helping developers to build solutions for deploying Hadoop YARN clusters in different environments. Once it is deployed in your favourite servlet container it exposes a REST API allowing to span up Hadoop clusters of arbitary sizes and cloud providers. Provisioning Hadoop has never been easier. Cloudbreak is built on the foundation of cloud providers API (Amazon AWS, Microsoft Azure, Google Cloud Platform, Openstack), Apache Ambari, Docker lightweight containers, Swarm and Consul. For further product documentation follow the link: <a href=\"http://hortonworks.com/apache/cloudbreak/\">http://hortonworks.com/apache/cloudbreak/</a>

    OpenAPI spec version: 2.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class StructuredFlowEvent(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'operation': 'OperationDetails',
        'flow': 'FlowDetails',
        'stack': 'StackDetails',
        'cluster': 'ClusterDetails',
        'blueprint': 'BlueprintDetails',
        'exception': 'str',
        'duration': 'int',
        'status': 'str'
    }

    attribute_map = {
        'type': 'type',
        'operation': 'operation',
        'flow': 'flow',
        'stack': 'stack',
        'cluster': 'cluster',
        'blueprint': 'blueprint',
        'exception': 'exception',
        'duration': 'duration',
        'status': 'status'
    }

    def __init__(self, type=None, operation=None, flow=None, stack=None, cluster=None, blueprint=None, exception=None, duration=None, status=None):
        """
        StructuredFlowEvent - a model defined in Swagger
        """

        self._type = None
        self._operation = None
        self._flow = None
        self._stack = None
        self._cluster = None
        self._blueprint = None
        self._exception = None
        self._duration = None
        self._status = None

        if type is not None:
          self.type = type
        if operation is not None:
          self.operation = operation
        if flow is not None:
          self.flow = flow
        if stack is not None:
          self.stack = stack
        if cluster is not None:
          self.cluster = cluster
        if blueprint is not None:
          self.blueprint = blueprint
        if exception is not None:
          self.exception = exception
        if duration is not None:
          self.duration = duration
        if status is not None:
          self.status = status

    @property
    def type(self):
        """
        Gets the type of this StructuredFlowEvent.

        :return: The type of this StructuredFlowEvent.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this StructuredFlowEvent.

        :param type: The type of this StructuredFlowEvent.
        :type: str
        """

        self._type = type

    @property
    def operation(self):
        """
        Gets the operation of this StructuredFlowEvent.

        :return: The operation of this StructuredFlowEvent.
        :rtype: OperationDetails
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """
        Sets the operation of this StructuredFlowEvent.

        :param operation: The operation of this StructuredFlowEvent.
        :type: OperationDetails
        """

        self._operation = operation

    @property
    def flow(self):
        """
        Gets the flow of this StructuredFlowEvent.

        :return: The flow of this StructuredFlowEvent.
        :rtype: FlowDetails
        """
        return self._flow

    @flow.setter
    def flow(self, flow):
        """
        Sets the flow of this StructuredFlowEvent.

        :param flow: The flow of this StructuredFlowEvent.
        :type: FlowDetails
        """

        self._flow = flow

    @property
    def stack(self):
        """
        Gets the stack of this StructuredFlowEvent.

        :return: The stack of this StructuredFlowEvent.
        :rtype: StackDetails
        """
        return self._stack

    @stack.setter
    def stack(self, stack):
        """
        Sets the stack of this StructuredFlowEvent.

        :param stack: The stack of this StructuredFlowEvent.
        :type: StackDetails
        """

        self._stack = stack

    @property
    def cluster(self):
        """
        Gets the cluster of this StructuredFlowEvent.

        :return: The cluster of this StructuredFlowEvent.
        :rtype: ClusterDetails
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """
        Sets the cluster of this StructuredFlowEvent.

        :param cluster: The cluster of this StructuredFlowEvent.
        :type: ClusterDetails
        """

        self._cluster = cluster

    @property
    def blueprint(self):
        """
        Gets the blueprint of this StructuredFlowEvent.

        :return: The blueprint of this StructuredFlowEvent.
        :rtype: BlueprintDetails
        """
        return self._blueprint

    @blueprint.setter
    def blueprint(self, blueprint):
        """
        Sets the blueprint of this StructuredFlowEvent.

        :param blueprint: The blueprint of this StructuredFlowEvent.
        :type: BlueprintDetails
        """

        self._blueprint = blueprint

    @property
    def exception(self):
        """
        Gets the exception of this StructuredFlowEvent.

        :return: The exception of this StructuredFlowEvent.
        :rtype: str
        """
        return self._exception

    @exception.setter
    def exception(self, exception):
        """
        Sets the exception of this StructuredFlowEvent.

        :param exception: The exception of this StructuredFlowEvent.
        :type: str
        """

        self._exception = exception

    @property
    def duration(self):
        """
        Gets the duration of this StructuredFlowEvent.

        :return: The duration of this StructuredFlowEvent.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """
        Sets the duration of this StructuredFlowEvent.

        :param duration: The duration of this StructuredFlowEvent.
        :type: int
        """

        self._duration = duration

    @property
    def status(self):
        """
        Gets the status of this StructuredFlowEvent.

        :return: The status of this StructuredFlowEvent.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this StructuredFlowEvent.

        :param status: The status of this StructuredFlowEvent.
        :type: str
        """

        self._status = status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, StructuredFlowEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
